server:
  port: 8081

spring:
  cloud:
    streams:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zk-nodes: 127.0.0.1:2181
      bindings:
        input-channel:
          destination: order-topic
