server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
#          brokers: kafka.dev.internal.seeyon.site:9092
          zk-nodes: 127.0.0.1:2182
      bindings:
        input:
          destination: channelin1,order-topic,channelin2
          group: g2
  kafka:
    topic-name:
      mytpc: order-topic