server:
  port: 8081

spring:
  cloud:
    streams:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
#          brokers: kafka.dev.internal.seeyon.site:9092
          zk-nodes: 127.0.0.1:2182
      bindings:
        input:
          destination: order-topic1
          group: g2
        channel1:
          destination: topic1
        channel2:
          destination: topic2
  kafka:
    topic-name:
      mytpc: order-topic