server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
#          brokers: kafka.dev.internal.seeyon.site:9092
          zk-nodes: 127.0.0.1:2182
        # 死信
        bindings:
          input:
            consumer:
              ## 所有服务都可发送 dlq
              enableDlq: true
              dlqName: ErrorTopic-listener
      bindings:
        input:
          destination: channelin2
          group: g2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create
