
server:
  port: 8089

spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 127.0.0.1:9092 # kafka.dev.internal.seeyon.site:9092
          brokers: 127.0.0.1:9092 # kafka.dev.internal.seeyon.site:9092
          #auto-add-partitions: true
          #auto-create-topics: true
          #min-partition-count: 1
        bindings:
          input-channel:
            consumer:
              ## 所有服务都可发送 dlq
              enableDlq: true
              dlqName: ErrorTopic
      bindings:
        input-channel: # channel
          destination: dest_topic # topic name
          group: grp1 # kafka group
        channel_out:
          destination: dest_topic