
server:
  port: 8089

spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 172.26.251.30:8182
          brokers: 172.26.251.30:9092

#            auto-add-partitions: true
#            auto-create-topics: false
#            min-partition-count: 1
        bindings:
          input-channel:
            consumer:
              ## 所有服务都可发送 dlq
              enableDlq: true
              dlqName: ErrorTopic
      bindings:
        input-channel: # channel
          destination: dest_topicname # topic name
          group: grp1 # kafka group
        channel_out:
          destination: dest_topicname
          group: grp1