server:
  port: 8088

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.26.205.232:9092
          zk-nodes: 172.26.205.232:2181
      bindings:
        output:
          destination: channelin1
        channel-out1:
          destination: order-topic
        channel-out2:
          destination: channelin2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create