server:
  port: 8088

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zk-nodes: 127.0.0.1:2181
          required-acks: -1
          auto-add-partitions: true
          auto-create-topics: true # 依赖broker的 auto.create.topics.enable
          transaction:
            transaction-id-prefix: tx-
      bindings:
        input:
          destination: channelin2
          group: 7
          consumer:
            enableDlq: true
            dlqName: ErrorTopic-listener
            autoCommitOffset: true
            concurrency: 7
        output:
          destination: order-topic
        channel-out:
          destination: concurrency-test
          producer:
            partition-count: 10 # 设置分区数，配合auto-add-partitions，会自动创建
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tester?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create