server:
  port: 8088

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka.dev.internal.seeyon.site:9092
          zk-nodes: kafka.dev.internal.seeyon.site:2181
      bindings:
        output:
          destination: channelin1
        channelin1:
          destination: order-topic
        channelin2:
          destination: channelin2
